# Use this only if SIM is enabled
#metricPrefix:  "Custom Metrics|Nginx|"

# If SIM is not enabled, then use this
metricPrefix:  "Server|Component:<TIER_ID>|Custom Metrics|Nginx|"
#To find the <COMPONENT_ID> in your environment,
#please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java

servers:
  - displayName: "Nginx Server" # mandatory
    uri: "http://localhost/nginx_status" # append port if needed
#    uri: "http://demo.nginx.com/" # append port if needed
    username: ""
    password: ""
    encryptedPassword:
    nginx_plus: "false"  # true for nginx-plus else false

encryptionKey: ""

connection:
  sslCertCheckEnabled: false
  socketTimeout: 10000
  connectTimeout: 10000

 # For each server you monitor, you will need a total of 12(by default) threads.
 # By default we want to support 3 servers, so it is 3 * 12 = 36 threads.
numberOfThreads: 36

