#prefix used to show up metrics in AppDynamics
metricPrefix:  "Custom Metrics|WebServer|NGinX"

#This will create it in specific Tier. Replace <TIER_ID>
#metricPrefix:  "Server|Component:<TIER_ID>|Custom Metrics|NginX Monitor|"

servers:
  - uri: "http://demo.nginx.com/status"
    name: "NGinX Monitor1" # mandatory
#   filter:
#      pools:
#        includes: [.*]

connection:
  sslCertCheckEnabled: false

numberOfThreads: 5
