# This will publish metrics to ONE tier only (recommended).
# Refer to the 'Metric Path' section of https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
# for instructions on how to retrieve the TIER_ID

#metricPrefix:  "Server|Component:<TIER_ID>|Custom Metrics|NGINX Monitor" #use if sim is disabled

metricPrefix:  "Custom Metrics|NGINX Monitor" #use only if sim is enabled

servers:
  - uri: "" # Please configure your endpoint as HOST_ENV_VARIABLE:PORT_ENV_VARIABLE
    name: "" # Mandatory
#   filter:
#      pools:
#        includes: [.*]

connection:
  sslCertCheckEnabled: false

numberOfThreads: 15
